### ISSUE TITLE
Could not trade because of the error thrown from `sendBuy`

### ISSUE THREAD

**Issue by DevMicke** [gas111-bot/gaspump-sdk#3]
Hello Everyone, 

I have been trying to automate my trades in your platform but using the code provided in your [README.md](https://github.com/gas111-bot/gaspump-sdk/blob/main/README.md) I could not make a transaction because code is throwing error from here:
```
await gaspumpJetton.sendBuy(sender, {
      tonAmount: buyTonAmount,
      doCheckTradeState: true,
 });
```

the error message is this: 

```
{
  err: Error: Not a number
      at TupleReader.readBigNumber (C:\Users\myuser\projects\gas-pump-bot-with-buy\node_modules\@ton\core\dist\tuple\reader.js:41:19)
      at loadTupleBondingCurveParams (C:\Users\myuser\projects\gas-pump-bot-with-buy\node_modules\@gaspump\sdk\src\contracts\GaspumpJetton.ts:8:29)
      at loadTupleFullJettonData (C:\Users\myuser\projects\gas-pump-bot-with-buy\node_modules\@gaspump\sdk\src\contracts\GaspumpJetton.ts:30:33)
      at GaspumpJetton.getFullJettonData (C:\Users\myuser\projects\gas-pump-bot-with-buy\node_modules\@gaspump\sdk\src\contracts\GaspumpJetton.ts:165:24)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async GaspumpJetton.sendBuy (C:\Users\myuser\projects\gas-pump-bot-with-buy\node_modules\@gaspump\sdk\src\contracts\GaspumpJetton.ts:89:36)
      at async main (C:\Users\myuser\projects\gas-pump-bot-with-buy\buy-bot.ts:59:5)
}
```
please someone help me

**Comment by DevMicke** [comment]
Nevermind it magically worked

**Comment by ggauzin** [comment]
> Nevermind it magically worked

it doesnt work on my side, would you mind sharing the code?
